//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string SourcePlace { get; set; }
        public string DestinationPlace { get; set; }
        public Nullable<System.DateTime> DateOfTravel { get; set; }
        public string AdharCard { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string Status { get; set; }
        public string MobileNo { get; set; }
    }
}
